[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pipecat-ai"
version = "0.2.0"
description = "Real-time AI pipelines for complex AI communications stacks"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Pipecat Team", email = "info@pipecat.ai"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "loguru>=0.7.2",
    "numpy>=1.24.0",
    "websockets>=10.4",
    "pydantic>=2.0.0",
]

[project.optional-dependencies]
dev = [
    "pre-commit",
    "black",
    "isort",
    "ruff",
    "pytest",
    "pytest-cov",
    "pytest-asyncio",
]
docs = [
    "sphinx>=7.0.0",
    "sphinx-rtd-theme>=1.0.0",
    "sphinx-autodoc-typehints>=1.15.0",
]
llm = [
    "openai>=1.0.0",
    "anthropic>=0.8.0",
    "langchain>=0.1.0",
]
tts = [
    "elevenlabs>=0.3.0",
]
stt = [
    "deepgram-sdk>=2.4.0",
    "whisper>=1.0",
]
all = [
    "pipecat-ai[dev,docs,llm,tts,stt]"
]

[project.urls]
"Homepage" = "https://pipecat.ai"
"Bug Tracker" = "https://github.com/pipecat-ai/pipecat/issues"
"Documentation" = "https://pipecat.readthedocs.io/"
"Source Code" = "https://github.com/pipecat-ai/pipecat"

[project.scripts]
pipecat = "pipecat.cli:main"

[tool.setuptools]
packages = {find = {where = ["src"]}}

[tool.black]
line-length = 100
target-version = ["py39", "py310", "py311"]

[tool.isort]
profile = "black"
line_length = 100

[tool.ruff]
line-length = 100
target-version = "py39"
select = ["E", "F", "B", "W"]
ignore = []
